version: '2'

services:
  http-proxy:
    build: ./src
    command: bash -c "./launch.sh"
    volumes:
      - data-volume:/var/log/erss
      - ./src:/code
    ports:
      - "12345:12345"
    tty: true

volumes:
  data-volume:
