version: '3.2'

services:
  http-proxy:
    build: ./src
    command: bash -c "./launch.sh"
    volumes:
      - type: bind
        source: ./var/log/erss
        target: /var/log/erss
    ports:
      - "12345:12345"
